import PageNation from "../../../../../components/PageNation/PageNation";
import { SinglePost } from "../../../../../components/Post/SinglePost";
import { getNumberOfPages, getPostByPage, getPostsByTagAndPage } from "../../../../../lib/notionAPI";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";


export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths:
    [
      { params : {tag: "blog", page: "1" } },
    ],
    fallback: "blocking",
  };
}

export const getStaticProps: GetStaticProps = async (context) => {
  const currentPage: string = context.params?.page!.toString();
  const currentTag: string = context.params?.tag!.toString();

  const posts = await getPostsByTagAndPage(currentTag, parseInt(currentPage, 10));
  return {
    props: {
      posts
    },
    revalidate: 60 * 60 * 6,
  }
}

const BlogTagPageList = ({ numberOfPage, posts }) => {

  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog🚀</h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {posts.map((post) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPagenationPage={true}
              />
            </div>
          ))}
        </section>
        <PageNation numberOfPage = {numberOfPage}/>
      </main>
    </div>
  );
}

export default BlogTagPageList;
